name: CI/CD Deploy to GCP Tomcat

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v0.1.7
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: workspace_project/Project

      - name: SSH 연결 테스트
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: echo "SSH 연결 성공"

      # 1. 임시 전송 위치(/home/kitsune950907/)의 기존 WAR 파일 삭제
      - name: Cleanup remote temp WAR file
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /home/kitsune950907/web.war

      # 2. WAR 파일을 임시 전송 위치에 복사
      - name: Copy WAR to Server via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "workspace_project/Project/target/web.war"
          target: "/home/kitsune950907/"
          overwrite: true
          debug: true

      # 3. 기존 배포 파일(폴더 및 WAR)을 삭제하여 깨끗한 상태로 만듦
      - name: Cleanup existing deployed WAR on Tomcat
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo systemctl stop tomcat9
            sudo rm -rf /var/lib/tomcat9/webapps/web /var/lib/tomcat9/webapps/web.war

      # 4. 임시 위치에 복사된 WAR 파일을 Tomcat 배포 경로로 이동 후 권한 변경 및 Tomcat 재시작
      - name: Deploy WAR on Tomcat
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mv /home/kitsune950907/web.war /var/lib/tomcat9/webapps/web.war
            sudo chown tomcat:tomcat /var/lib/tomcat9/webapps/web.war
            sudo systemctl start tomcat9